/** Echte Kuriositäts-/Aktionstage je Kalendertag ("MM-DD"), aus dem etablierten
 *  Jahreskalender von kuriose-feiertage.de (kuriose-feiertage.de/kalender/) – 338 von 365 Tagen
 *  abgedeckt, 842 Einträge insgesamt. Genutzt von ensureDailyThemes in
 *  station-engine.ts als echte, verifizierte Grundlage fürs Tagesthema, statt es komplett von
 *  der KI erfinden zu lassen. Tage ohne Eintrag fallen weiter auf die KI-Erfindung zurück. */
export const CURIOSITY_DAYS: Record<string, string[]> = {
  "01-01": ["Neujahrstradition des First-Footing in Schottland","Tag des Glücksschweins in Deutschland","Bonza-Bottler-Day in den USA"],
  "01-02": ["Science-Fiction-Tag am 2. Januar – National Science Fiction Day in den USA"],
  "01-03": ["Der internationale Women Rock! Day","Der internationale J.R.R. Tolkien Day am 3. Januar – Happy Birthday Tolkien!","Feiertag des Schlafens  – der US-amerikanische Festival of Sleep Day","Tag des Strohhalms am 3. Januar – National Drinking Straw Day in den USA"],
  "01-04": ["Tag der Mandarine in Deutschland"],
  "01-05": ["Tag des Vogels – National Bird Day in den Vereinigten Staaten"],
  "01-06": ["Nollaig na mBan – Women’s Christmas oder Little Christmas in Irland","Tag der Frau Holle in Europa – oder: das Ende der Rauhnächte","La befana oder die Nacht der Weihnachtshexe Befana in Italien","Tag der Bohne – der US-amerikanische National Bean Day"],
  "01-07": ["Tag des Spinnrockens – St. Distaff‘s Day","International Silly Walks Day","Furz-Tag in den USA – National Pass Gas Day"],
  "01-08": ["Tag des Argyle-Musters – der US-amerikanische National Argyle Day","Fest der Frauen in Griechenland – die Tradition des Yinekokratia","Tag des English Toffee am 8. Januar – National English Toffee Day in den USA"],
  "01-09": ["Spiele-Gott-Tag – der US-amerikanische Play God Day"],
  "01-10": ["Internationaler Depeche-Mode-Tag – Depeche Mode Day","Tag der Typen am 10. Januar – Peculiar People Day in den Vereinigten Staaten","Rettet-die-Adler-Tag – der US-amerikanische Save the Eagles Day","Der bundesweite Tag der Blockflöte in Deutschland"],
  "01-11": ["Der internationale No Pants Subway Ride – Aktionstag","Internationaler Dankeschön-Tag – der International Thank You Day","Tag der Milch am 11. Januar – National Milk Day in den Vereinigten Staaten","Tag des deutschen Apfels – bundesweiter Aktionstag"],
  "01-12": ["Der internationale Weltschafkopftag","Chicken-Curry-Tag am 12. Januar – National Curried Chicken Day in den USA"],
  "01-13": ["Tag des Quietscheentchens am 13. Januar – Rubber Ducky Day in den USA","St. Knut-Tag in Skandinavien"],
  "01-14": ["Welttag der Logik – der internationale World Logic Day"],
  "01-15": ["Tag des Bagels – der US-amerikanische National Bagel Day"],
  "01-16": ["Internationaler Fetisch-Tag – International Fetish Day"],
  "01-17": ["Tag der italienischen Küche am 17. Januar – International Day of italian cuisines","Tag der Kinder-Erfinder – der US-amerikanische Kid Inventors&#8216; Day","Tag der Kabelstraßenbahn – der US-amerikanische Cable Car Day"],
  "01-18": ["World Snow Day – der internationale Welt-Schnee-Tag","Tag des Gourmetkaffees am 18. Januar – National Gourmet Coffee Day in den USA","Thesaurus-Tag am 18. Januar – National Thesaurus Day in den USA"],
  "01-19": ["Blue Monday – der traurigste Tag des Jahres","Welt-Quark-Tag – World Quark Day","Der Martin Luther King Jr. Day in den USA","Tag des Popcorns am 19. Januar – der National Popcorn Day in den USA"],
  "01-20": ["Tag der Pinguine am 20. Januar – Penguin Awareness Day in den USA","Tag der Käseliebhaber am 20. Januar – National Cheese Lovers Day in den USA"],
  "01-21": ["Der internationale Museum Selfie Day – #MuseumSelfie Day","Internationaler Jogginghosentag – International Sweatpants Day","Weltknuddeltag – der (Inter-)National Hugging Day"],
  "01-22": ["Tag des Punktmusters am 22. Januar – National Polka Dot Day in den USA","Tag der scharfen Saucen am 22. Januar – National Hot Sauce Day in den USA"],
  "01-23": ["Kuchen-Tag am 23. Januar – National Pie Day in den USA","Tag der Handschrift am 23. Januar – National Handwriting Day in den USA"],
  "01-24": ["Ehrentag der Bierdose am 24. Januar – Beer Can Appreciation Day in den USA","Tag der Erdnussbutter am 24. Januar – National Peanut Butter Day in den USA"],
  "01-25": ["Tag der Heiligen Dwynwen – der walisische Saint Dwynwen’s Day","Burns Supper in Schottland – ein Abend zu Ehren von Robert Burns","Gegenteiltag – der US-amerikanische National Opposite Day"],
  "01-26": ["Tag der Ehepartner am 26. Januar – National Spouses Day in den Vereinigten Staaten","Versteck-einen-Kuchen-Tag am 26. Januar – der US-amerikanische Hide a Cake Day","Tag des Kohlsafts – der US-amerikanische National Green Juice Day","Australia Day 2026 – der australische Nationalfeiertag"],
  "01-27": ["Thomas Crapper Day in Großbritannien","Tag der eulerschen Zahl – der internationale e-Day am 27. Januar und 7. Februar"],
  "01-28": ["Europäischer Datenschutztag – der EU Data Protection Day","Der US-amerikanische National Library Shelfie Day","Internationaler LEGO-Tag am 28. Januar – International LEGO Day","Tag der Kazoo am 28. Januar – National Kazoo Day in den USA","Der US-amerikanische Fun at Work Day"],
  "01-29": ["Tag der Nelken am 29. Januar – der US-amerikanische National Carnation Day","Tag der Maischips am 29. Januar – National Corn Chip Day in den USA","Tag des Puzzles in den Vereinigten Staaten – National Puzzle Day"],
  "01-30": ["Tag der Saudade – der Dia da Saudade in Brasilien","Tag der Alltagsflucht – der US-amerikanische National Escape Day","Tag des Croissants am 30. Januar – der US-amerikanische National Croissant Day"],
  "01-31": ["Internationaler Zebra-Tag – International Zebra Day"],
  "02-01": ["Tag des Eurasiers in Deutschland – 1. Februar – Happy Birthday für Eddy, den Eurasier Blindenhund","Der US-amerikanische Hula in the Coola Day zum anstehenden Winterande","Tag der Schlange am 1. Februar – National Serpent Day in den Vereinigten Staaten"],
  "02-02": ["Tag der Tater Tots am 2. Februar – National Tater Tot Day in den Vereinigten Staaten","Küünlapäev in Estland – Kerzentag zu Mariä Lichtmess","Tag des arbeitslosen Duftbaums"],
  "02-04": ["Weltkrebstag 2026 – World Cancer Day – Internationaler Aktionstag","Erzeuge-ein-Vakuum-Tag – der US-amerikanische Create a Vacuum Day"],
  "02-05": ["Runeberg-Tag in Finnland – Runebergin päivä","Welt-Nutella-Tag – World Nutella Day"],
  "02-06": ["Dicker-Pulli-Tag in Deutschland – Aktionstag zum Energiesparen","Internationaler Bob-Marley-Tag – Bob Marley Day auf Jamaika","International Clash Day – der internationale Ehrentag für The Clash","Bubblegum-Tag in den Vereinigten Staaten – Bubble Gum Day","Zieh-etwas-Rotes-an-Tag in den USA – National Wear Red Day"],
  "02-07": ["Tag der eulerschen Zahl – der internationale e-Day am 27. Januar und 7. Februar","Rosentag als Auftakt der Valentins-Woche – der Rose Day"],
  "02-08": ["Tag der Oper – National Opera Day am 8. Februar und World Opera Day"],
  "02-09": ["Kack-Tag in den Vereinigten Staaten – National Poop Day"],
  "02-10": ["Internationaler Tag der Hülsenfrüchte – World Pulses Day","Flanell-Tag – der US-amerikanische National Flannel Day","Tag der doofen Nuss am 10. Februar – ein kurioser Büro-Feiertag aus Deutschland","Internationaler Tag des Feuerlöschers – International Fire Extinguisher Day"],
  "02-11": ["Europäischer Tag des Notrufes 112 – der European 112 Day","Sei-elektrisierend-Tag – der US-amerikanische Be Electrific Day"],
  "02-12": ["Tag des Reibekuchens in Deutschland – Weiberfastnacht 12. Februar","Tag der Umarmung – der sechste Tag der indischen Valentinswoche","Darwin-Tag – International Darwin Day zu Ehren des Naturforschers"],
  "02-13": ["Galentine’s Day – Ehrentag für die weibliche Freundschaft","Cheddar-Tag am 13. Februar – National Cheddar Day in den USA","Welttag des Radios – der internationale UNESCO World Radio Day","Kuss-Tag – der siebte Tag der Valentinswoche in Indien"],
  "02-14": ["Welt-Mettbrötchen-Tag","Valentinstag – Ehrentag des heiligen Valentin St. Valentine’s Day"],
  "02-15": ["Anti-Valentinstag für Singles – der britische St. Skeletor’s Day","Ehrentag der Singles am 15. Februar – Singles Awareness Day in den USA","Tag der Gummidrops in den USA – National Gumdrop Day"],
  "02-16": ["Happy Birthday George Washington – Presidents‘ Day in den USA","Tag der Mandel – der US-amerikanische National Almond Day"],
  "02-18": ["Nichtrauchertag in Irland – National No Smoking Day","Pluto Day – der internationale Tag der Entdeckung Plutos"],
  "02-19": ["Tag der Wimpern – der US-amerikanische National Lash Day"],
  "02-20": ["Der bundesweite Toast-Hawaii-Tag in Deutschland","Welt-Pfeifenraucher-Tag – International Pipe Smoking Day"],
  "02-21": ["Weltgästeführertag am 21. Februar – International Tourist Guide Day","World Whale Day auf Maui – Welttag der Wale"],
  "02-22": ["Tag der Fähren am 22. Februar – Aktionstag für Fährreisen in Europa zum Petritag","Neko no hi oder Neko-no-kinenbi – Katzentag in Japan","Single-Tasking-Tag – der US-amerikanische Single Tasking Day","Tag der Wildtiere am 22. Februar und 4. September – National Wildlife Day in den USA","Tag der Weißwurst in Deutschland am 22. Februar – die ersten Weißwürste werden serviert"],
  "02-23": ["Welttag der Waschmaschine in Deutschland","Spiel-Tennis-Tag – der US-amerikanische Play Tennis Day"],
  "02-25": ["Welttag der Lesezeichen am 25. Februar – World Bookmark Day","Sei-unbequem-Tag in den USA – Inconvenience Yourself Day","Tag der Schachtelsätze am 25. Februar – Ehrentag der Hypotaxe in Deutschland"],
  "02-26": ["Tag des Jahrmarkts am 26. Februar – der National Carnival Day in den USA","Levi Strauss Day in den USA – Happy Birthday Loeb Strauss","Tag des Ringfingers – der US-amerikanische Ring Finger Day","Tag des Chilis in den USA – National Chili Day"],
  "02-27": ["Der internationale Pokémon-Tag – Pokémon Day","Welteisbärentag – International Polar Bear Day"],
  "02-28": ["Internationale Open That Bottle Night – Öffene-diese-eine-Flasche-Nacht","Tag der Floristik – der US-amerikanische National Floral Design Day"],
  "02-29": ["Schalttag und Schaltjahr – eine kalendarische Kuriosität"],
  "03-01": ["Tag der Hand – bundesweiter Aktionstag in Deutschland","Tag des Schweins – der US-amerikanische National Pig Day","Welttag der Komplimente am 1. März – der World Compliment Day"],
  "03-02": ["Adoptiere-eine-Katze-Tag am 2. März – International Rescue Cat Day","Tag der alten Dinge am 2. März – National Old Stuff Day in den Vereinigten Staaten","Dr. Seuss Day in den USA – Happy Birthday Theodor Seuss Geisel"],
  "03-03": ["Tag des Aufschnitts am 3. März – National Cold Cuts Day in den Vereinigten Staaten","Tag des Artenschutzes – der United Nations World Wildlife Day"],
  "03-04": ["Tag der Snacks – der US-amerikanische National Snack Day","Der US-amerikanische March Forth and Do Something Day","Internationaler Scrapbooking-Tag am 4. März – International Scrapbooking Day"],
  "03-05": ["World Book Day – der Welttag des Buches in Irland und Großbritannien"],
  "03-06": ["Zahnarzt-Tag am 6. März – National Dentist’s Day in den USA","Tag des Kleides – der US-amerikanische National Dress Day","Tag der Tiefkühlkost – der US-amerikanische National Frozen Food Day"],
  "03-07": ["Alexander Graham Bell Day im kanadischen Nova Scotia","Tag der Frühstücksflocken am 7. März – National Cereal Day in den USA"],
  "03-08": ["Sei-frech-Tag am 8. März – der National Be Nasty Day in den Vereinigten Staaten"],
  "03-09": ["Tag der Fleischbällchen am 9. März – National Meatball Day in den Vereinigten Staaten"],
  "03-10": ["Tag der Röcke – der US-amerikanische National Skirt Day","Internationaler Dudelsack-Tag – der International Bagpipe Day","Super-Mario-Tag – der US-amerikanische Mario Day"],
  "03-12": ["Milky-Way-Tag – der US-amerikanische National Milky Way Day"],
  "03-13": ["Welttag des Schlafes – der internationale World Sleep Day","Tag des Edelsteins am 13. März – National Jewel Day in den Vereinigten Staaten","Tag der Ohrenschützer – der US-amerikanische National Earmuff Day"],
  "03-14": ["Indiebookday in Deutschland, Österreich und der Schweiz","Tag der Zahl Pi – der internationale Pi Day zu Ehren der Kreiszahl Pi"],
  "03-15": ["Der bundesweite Tag der Druckkunst in Deutschland"],
  "03-16": ["Tag des Reisfladens – ein kulinarischer Feiertag am 16. März in Belgien und Deutschland","Tag des Pandas – der US-amerikanische National Panda Day","Tag des Schluckaufs – der US-amerikanische National Hiccup Day"],
  "03-17": ["Tag des Tauchboots in Großbritannien – Submarine Day"],
  "03-18": ["Global Recycling Day am 18. März  – der internationale Welt-Recycling-Tag"],
  "03-19": ["Tag der Luftretter in Deutschland 2026 – Aktionstag","Tag des Geflügels – der US-amerikanische National Poultry Day","Lass-uns-lachen-Tag – der US-amerikanische Let’s Laugh Day"],
  "03-20": ["Welttag der Frösche am 20. März – World Frog Day","Tag der Bibliomanie am 20. März – Bibliomania Day in den USA"],
  "03-21": ["Tattoo-Tag – World Tattoo Day am 21. März und National Tattoo Day","Welt-Down-Syndrom-Tag am 21. März – der World Down Syndrome Day","Internationaler Tag der Farbe am 21. März – der International Colour Day"],
  "03-22": ["Tag des Berliner Bären in Deutschland","World Doula Day 2026 – Welttag der Doulas","Tag des Faulenzens am 22. März – National Goof-Off Day in den Vereinigten Staaten"],
  "03-24": ["Harry Houdini Tag – der US-amerikanische Harry Houdini Day","Elefanten-zeichnen-Tag in Deutschland"],
  "03-25": ["Trandagen in Schweden – Kranich-Tag oder die Rückkehr der Kraniche","Ehrentag der Seekühe in den USA – Manatee Appreciation Day","European Talent Day – Tag der Talente","Tag der Tolkien-Lektüre – Tolkien Reading Day","Våffeldagen am 25. März – der landesweite Tag der Waffel in Schweden","Internationaler Document Freedom Day für offene digitale Standards"],
  "03-26": ["Tag des Spinats am 26. März – National Spinach Day in den USA","Tag des Nougats am 26. März – National Nougat Day in den Vereinigten Staaten"],
  "03-27": ["Welttag des Theaters – World Theatre Day","Tag des Joe am 27. März – der US-amerikanische National Joe Day"],
  "03-28": ["Tag der Eierausstellung am 28. März – Eggsibit Day in den Vereinigten Staaten","Earth Hour – Licht aus für das Klima – internationaler Aktionstag"],
  "03-29": ["Einmal-am-Tag-etwas-Verrücktes-tun-Tag in Deutschland","Welt-Piano-Tag – der internationale World Piano Day"],
  "03-30": ["Internationaler Zero-Waste-Tag am 30. März – International Day of Zero Waste","Ärzte-Tag – der US-amerikanische National Doctors&#8216; Day","Tag des Bleistifts – der US-amerikanische National Pencil"],
  "03-31": ["Tag der Wachsmalstifte am 31. März – National Crayola Crayon Day in den USA"],
  "04-01": ["Tag der essbaren Bücher – International Edible Book Day","Internationaler Occhi-Tag – International Tatting Day"],
  "04-02": ["Tag der Burritos in den USA – National Burrito Day","Weltmaultaschentag – immer parallel zum Gründonnerstag"],
  "04-03": ["Welt-Murmel-Tag om Großbritanien – World Marbles Day","Welttag der Wassertiere am 3. April – World Aquatic Animal Day","Tag der Arschkarte – die erste Rote Karte der Fußball-Bundesliga","Finde-einen-Regenbogen-Tag am 3. April – Find a Rainbow Day in den USA"],
  "04-04": ["404-Tag – der US-amerikanische 404 Day","Weltschlagzeugertag am 4. April – World Drummer’s Day"],
  "04-05": ["Tag der Geologen in Osteuropa – internationaler Geologist Day","Tag des Ersten Kontakts – der First Contact Day in Star Trek"],
  "04-06": ["Tag der frischen Tomaten am 6. April – National Fresh Tomato Day in den USA","Tag des Teflons am 6. April – der US-amerikanische National Teflon Day","Internationaler Tag des Sports für Entwicklung und Frieden","Tartan Day zu Ehren der Declaration of Arbroath in Kanada und den USA"],
  "04-07": ["Internationaler Tag der Biber am 7. April – der International Beaver Day","Nationaler Tag des Bieres in den USA – National Beer Day","Keine-Hausarbeit-Tag – der US-amerikanische No Housework Day"],
  "04-08": ["Der US-amerikanische Rex Manning Day","Das japanische Blumenfest Hana Matsuri","Zeichne-einen-Vogel-Tag in Großbritannien – Draw a Bird Day"],
  "04-09": ["National Winston Churchill Day am 9. April – Winston-Churchill-Tag in den USA"],
  "04-10": ["Tag der Golfer am 10. April – National Golfers Day in den USA","Tag des Schweigens in den USA – National Day of Silence"],
  "04-11": ["Tag der Freesien in Deutschland"],
  "04-12": ["Welttag der Hamster – World Hamster Day oder Hamster Day","Tag der Einzelkinder – der US-amerikanische National Only Child Day","Zeig-Deine-wilde-Seite-Tag am 12. April – Walk on your Wild Side Day in den USA"],
  "04-14": ["Tag der Delfine – National Dolphin Day am 14. April und World Dolphin Day"],
  "04-15": ["Tag der Banane in den USA – Banana Day"],
  "04-16": ["World Semicolon Day – der internationale Welttag des Semikolons","Gib-mir-Fünf-Tag in den USA – National High Five Day","Tag der Orchidee am 16. April – National Orchid Day in den Vereinigten Staaten"],
  "04-17": ["Welttag des Malbec am 17. April – der internationale Malbec World Day","Welttag der Hämophilie am 17. April – der internationale World Hemophilia Day","BlaBlabBla-Tag – der US-amerikanische Blah, Blah, Blah Day"],
  "04-18": ["Tag der Tier-Kekse am 18. April – National Animal Crackers Day in den USA"],
  "04-19": ["Bicycle Day – Albert Hofmann unternimmt am 19. April eine Radtour auf LSD"],
  "04-20": ["Tag der Cheddar Fries am 20. April – National Cheddar Fries Day in den USA","Tag der chinesischen Sprache – UNESCO Chinese Language Day"],
  "04-21": ["Tag der langen Wörter am 21. April – der US-amerikanische Big Word Day","Tag des berühmtesten Nessie-Fotos"],
  "04-22": ["Tag der Aprilschauer – der US-amerikanische April Showers Day"],
  "04-23": ["Internationaler Ramones-Tag am 23. April – International Ramones Day","Internationaler Tag der Pallaskatze am 23. April – International Pallas’s Cat Day","World Book Night in UK, Irland und den USA","Vespa-Tag – Piaggio lässt am 23. April 1946 die Vespa patentieren","Welttischtennistag – der internationale World Table Tennis Day","Welttag des Buches und des Urheberrechts am 23. April – Weltbuchtag"],
  "04-24": ["Internationaler Tag der Streuobstwiese in Europa","Der internationale Fashion Revolution Day am 24. April 2026 #whomademyclothes"],
  "04-25": ["Weltmalariatag – World Malaria Day – internationaler Aktionstag","Tag der Astronomie in den USA – National Astronomy Day am 25. April und 19. September","Internationaler Tag der Tierärzte – der World Veterinary Day","Internationaler Tag der Skulptur – International Sculpture Day","Welt-Pinguin-Tag am 25. April – der internationale World Penguin Day"],
  "04-26": ["Internationaler Tag der Flamingos – International Flamingo Day"],
  "04-27": ["Welttag der Möwen – World Seagull Day"],
  "04-28": ["Tag der Cracker – der US-amerikanische National Cracker Day","Tag des Blaubeerkuchens am 28. April – National Blueberry Pie Day in den USA"],
  "04-29": ["Tag der Superhelden am 29. April – National Superhero Day in den Vereinigten Staaten","Tag der Gloria Dei am 29. April – National Peace Rose Day in den USA","Tag gegen Lärm – International Noise Awareness Day","Tag des Reißverschlusses am 29. April – National Zipper Day in den USA","Welttag des Tanzes am 29. April – der UNESCO International Dance Day"],
  "04-30": ["Der bundesweite Tag des Wolfes – Aktionstag in Deutschland","Walpurgisnacht am 30. April – Hexenbrennen in der Nacht zum 1. Mai","Tag der Rosine – der US-amerikanische National Raisin Day","Welttag des Jazz am 30. April – UNESCO International Jazz Day","Poem in your Pocket Day in den Vereinigten Staaten"],
  "05-01": ["Internationaler Tag der Tuba – der International Tuba Day","Ohne-Hose-Tag – der internationale No Pants Day","Vappu – das finnische Frühlingsfest zum 1. Mai"],
  "05-02": ["Der internationale Blue Switch Day","Tag der Kräuter in den USA – National Herb Day","Weltfischbrötchentag in Schleswig-Holstein"],
  "05-03": ["Tag der Teppichfalte – der US-amerikanische Lumpy Rug Day","Weltlachtag – World Laughter Day"],
  "05-04": ["Tag der Gyoza in Deutschland","Tag des Orangensafts am 4. Mai – National Orange Juice Day in den USA","Star-Wars-Tag oder: Star Wars Day – May the 4th be with you"],
  "05-05": ["Tag des Deutschen Brotes – bundesweiter Aktionstag","Tag des herzkranken Kindes – bundesweiter Aktionstag in Deutschland","Internationaler Hebammentag – der International Midwives&#8216; Day"],
  "05-06": ["World Accordion Day – Internationaler Tag des Akkordeons","Der internationale Weltkindermaltag","Internationaler Anti-Diät-Tag am 6. Mai – der International No Diet Day"],
  "05-07": ["Tag der Vernunft in den USA – National Day of Reason"],
  "05-08": ["Welttag der Esel – der internationale World Donkey Day","Tag der Schwertlilie am 8. Mai – National Iris Day in den Vereinigten Staaten"],
  "05-09": ["International Chameleon Day – Internationaler Tag des Chamäleons","Welttag des Bonsai – World Bonsai Day","Der bundesweite Deutsche Sekttag","Foodie-Tag am 9. Mai – National Foodies Day in den Vereinigten Staaten","Minigolf-Tag in den USA – National Miniature Golf Day","Eisenbahn-Tag in den Vereinigten Staaten – der National Train Day"],
  "05-10": ["Internationaler Tag des Kaktus – World oder National Cactus Day in den USA","Mother Ocean Day 2026 – internationaler Mutter-Ozean-Tag","Muttertag in Deutschland am zweiten Sonntag im Mai","International Monty Python Status Day – Monty-Python-Status-Tag","Tag der Windmühle – der US-amerikanische National Windmill Day","One Day Without Shoes Day"],
  "05-11": ["Tag der gleichfarbigen Socken in Deutschland","Beginn der Eisheiligen","Tag der Kinderbetreuung in Deutschland"],
  "05-13": ["Welt-Cocktail-Tag am 13. Mai – World Cocktail Day"],
  "05-14": ["Der bundesweite Vatertag in Deutschland an Christi Himmelfahrt","Yellow Day oder: 로즈데이 – Tag der gelben Rosen in Südkorea","Tag des Wanderns – der bundesweite Wandertag in Deutschland"],
  "05-15": ["Tag des Fahrradflickzeugs in Deutschland","Tag des Strohhuts in Großbritannien – der (National) Straw Hat Day"],
  "05-16": ["International Metalheads Day am 16. Mai – RIP Ronnie James Dio","World Whisky Day – Welt-Whisky-Tag"],
  "05-17": ["Tag der Armlehne in Deutschland"],
  "05-18": ["I Love Reese’s Day in den Vereinigten Staaten und Kanada","Internationaler Museumstag am 18. Mai – International Museum Day"],
  "05-20": ["Der bundesweite Fremdworttag in Deutschland"],
  "05-21": ["Welttrinkgeldtag – bundesweiter Aktionstag","Sprich-wie-Yoda-Tag – der internationale Talk Like Yoda Day","Internationaler Tee-Tag – der International Tea Day am 21. Mai und","Tag der Notizzettel am 21. Mai – National Memo Day  in den Vereinigten Staaten","Weltuntergangstag – Rapture Party Day in den USA"],
  "05-22": ["Der bundesweite Tag des Schwimmmeisters in Deutschland","Sherlock-Holmes-Tag – der International Sherlock Holmes Day","World Goth Day – internationaler Tag der Gothic-Szene"],
  "05-23": ["Weltschildkrötentag am 23. Mai – der internationale World Turtle Day"],
  "05-24": ["Iss-eine-Kiwi-Tag in Deutschland"],
  "05-25": ["Der internationale Geek Pride Day","Tag des Weins in den USA – National Wine Day","Towel Day am 25. Mai – der intergalaktische Handtuchtag zu Ehren von Douglas Adams"],
  "05-26": ["Welttag der Rothaarigen – World Redhead Day"],
  "05-27": ["Welttag der Otter – der internationale World Otter Day","Tag der Sonnencreme am 27. Mai – National Sun Screen Day in den USA","Tag des Klebebands am 27. Mai – National Cellophane Tape Day in den USA","Welttag des Purzelbaums – der internationale Ehrentag der Turnrolle"],
  "05-28": ["Tag des Hamburgers – National und International Hamburger Day","Weltspieltag oder Welttag des Spielens – World Play Day"],
  "05-29": ["Keks-Tag in Großbritannien – der britische National Biscuit Day"],
  "05-30": ["Welttag der Seelöwen am 30. Mai – der internationale World Sea Lion Day","Tag des Mint Julep am 30. Mai – National Mint Julep Day in den Vereinigten Staaten","Dìa Nacional De La Papa am 30. Mai – der Nationaltag der Kartoffel in Peru","Gieß-eine-Blume-Tag – der US-amerikanische Water a Flower Day"],
  "05-31": ["Tag der Weißstörche in Polen – Dzień Bociana Białego","Weltnichtrauchertag am 31. Mai – World No Tobacco Day"],
  "06-01": ["Welttag der Riffe – World Reef Awareness Day – Aktionstag","Internationaler Kindertag – Aktionstag"],
  "06-03": ["Welt-Apfelwein-Tag – World Cider Day","Der bundesweite Tag der Amsel in Deutschland","Welttag des Laufens – Global Running Day","Tag der Eier in den USA – National Egg Day","Europäischer Tag des Fahrrads und Weltfahrradtag"],
  "06-05": ["Tag des Lebkuchens am 5. Juni – National Gingerbread Day in den Vereinigten Staaten","Ketchup-Tag – der US-amerikanische National Ketchup Day","Weltumwelttag am 5. Juni – UNO World Environment Day"],
  "06-06": ["Tag der Organspende in Deutschland","Internationaler Tag der Höhlen und der unterirdischen Welten am 6. Juni und 13. September","Tag des Jo-Jos – der US-amerikanische National Yo-Yo Day"],
  "06-07": ["Tag des Modellflugs in Deutschland","Tag der Apotheke in Deutschland – bundesweiter Aktionstag","Welt-Naturisten-Tag – der internationale World Naturist Day","Tag des Videorekorders am 7. Juni – National VCR Day in den USA"],
  "06-08": ["Tag des Erdbeerkäsekuchens – Strawberry Cheesecake Day","Der internationale Ghostbusters Day – Erinnerung an den US-Kinostart","Beste-Freunde-Tag am 8. Juni und 15. August – National Best Friends Day in den USA","Hoppla-Tag am 8. Juni – National Upsy Daisy Day in den Vereinigten Staaten","Tag des Meeres am 8. Juni – UNO World Oceans Day"],
  "06-09": ["Internationaler Tag der Archive am 9. Juni – International Archives Day","Donald Ducks Geburtstag – der US-amerikanische Donald Duck Day"],
  "06-10": ["Internationaler Tag der Heraldik am 10. Juni – International Heraldry Day"],
  "06-11": ["Tag der Geodäsie in Deutschland"],
  "06-12": ["Superman-Tag – der US-amerikanische Superman Day","Loving-Tag in den USA – National Loving Day","Tag des Tagebuchs in Deutschland"],
  "06-13": ["Tag der Tauben in den Vereinigten Staaten – National Pigeon Day","Welttag des Gins – World Gin Day","Tag der Nähmaschine in den USA – National Sewing Machine Day"],
  "06-14": ["Internationaler Bade-Tag – der International Bath Day","Tag des Gartens in Deutschland – Aktionstag","Tag des Bourbons in den USA – National Bourbon Day"],
  "06-15": ["Der bundesweite Tag des Strandkorbs in Deutschland","Global Wind Day am 15. Juni – Weltwindtag"],
  "06-16": ["Internationaler Tag des Wasserfalls – der International Waterfall Day","Tag der Cannoli – der US-amerikanische National Cannoli Day"],
  "06-17": ["Welttag der Krokodile – World Crocodile Day oder World Croc Day","Internationaler Tag der Müllabfuhr – der Global Garbage Man Day","Iss-Dein-Gemüse-Tag in den USA – National Eat Your Vegetables Day","Tag des Apfelstrudels am 17. Juni – National Apple Strudel Day in den USA"],
  "06-18": ["Internationaler Sushi-Tag am 18. Juni – International Sushi Day","Gönn-Dir-was-Tag – der US-amerikanische National Splurge Day","Internationaler Panik-Tag oder keine Panik – der International Panic Day"],
  "06-19": ["Garfield-Tag am 19. Juni – National Garfield the Cat Day in den Vereinigten Staaten"],
  "06-20": ["Tag der Filtertüte in Deutschland zu Ehren von Melitta Bentz"],
  "06-21": ["Tag der langen Menschen","Der bundesweite Mofa-Tag in Deutschland","Welttag der Dackel – World Dachshund Day","Welttag der Giraffe am 21. Juni – der internationale World Giraffe Day","Muschel-Tag in den USA – National Seashell Day","Der bundesweite Tag der Musik in Deutschland – Aktionstag","Internationaler T-Shirt-Tag am 21. Juni – International T-Shirt Day","Der bundesweite Tag des Schlafes in Deutschland am 21. Juni (von 2000 bis 2003)"],
  "06-22": ["Welttag der Kamele – World Camel Day","Weltregenwaldtag – World Rainforest Day"],
  "06-23": ["Loslassen-Tag in den USA – Let it Go Day"],
  "06-24": ["Johannistag und Johannisnacht"],
  "06-25": ["Welttag der Schulfreunde","Tag des Handschlags in den USA – National Handshake Day"],
  "06-26": ["Welttag der Kältetechnik – World Refrigeration Day","Tag des Kanus 2026 – der kanadische National Canoe Day","Bärengedenktag in Deutschland am 26. Juni – Gedenktag für den Bären Bruno JJ 1"],
  "06-27": ["Der bundesweite Tag des Deutschen Whiskys","Tag der Zwiebel am 27. Juni – der National Onion Day in den Vereinigten Staaten","Internationaler Tag der Schlümpfe – der Global Smurfs Day","Siebenschläfertag in Deutschland – die sieben Schläfer von Ephesus","Internationaler Tag der Ananas – der International Pineapple Day"],
  "06-28": ["Tag der alternativen Kreiszahl Tau – der internationale Tau Day","Paul-Bunyan-Tag am 28. Juni – National Paul Bunyan Day in den Vereinigten Staaten"],
  "06-29": ["Internationaler Tag der Fischer – International Fisherman’s Day","Internationaler Tag der Tropen am 29. Juni – International Day of the Tropics","Internationaler Matsch-Tag – der International Mud Day","Tag der Kamera – der US-amerikanische National Camera Day"],
  "06-30": ["Mai-Tai-Tag am 30. Juni – National Mai Tai Day in den USA","Tag des Meteors – Meteor Day zur Erinnerung an das Tunguska-Ereignis"],
  "07-01": ["Tag der Litfaßsäule in Deutschland","Internationaler Witze-Tag 2026 – der International Joke Day","July Morning in Bulgarien – eine Hippie-Tradition zum 1. Juli"],
  "07-02": ["Tag des Anisette am 2. Juli – National Anisette Day in den USA","Welt-UFO-Tag am 2. Juli – World UFO Day"],
  "07-04": ["Tag der Gießkanne in Deutschland – bundesweiter Aktionstag","Die National Tom Sawyer Days in den Vereinigten Staaten","Geh-in-den-Park-Tag in den USA – National Hop A Park Day"],
  "07-06": ["Eino Leinon päivä am 6. Juli – Finnland feiert den Geburtstag von Eino Leino","Internationaler Tag des Kusses – International Kissing Day"],
  "07-07": ["Tag des Freibads – bundesweiter Aktionstag in Deutschland","Tag der Makkaroni am 7. Juli – National Macaroni Day in den Vereinigten Staaten","Sag-die-Wahrheit-Tag am 7. Juli – National Tell The Truth Day in den USA","Tag der Schokolade am 7. Juli – National Chocolate Day in den USA","Tanabata in Japan oder die Tradition des japanischen Sternenfests"],
  "07-08": ["Tag der Videospiele – der US-amerikanische Video Games Day","Jährliche Totenwache für Soapy Smith – Annual Soapy Smith Wake"],
  "07-09": ["Fernweh-Tag am 9. Juli – Call of the Horizon Day in den Vereinigten Staaten"],
  "07-10": ["Kätzchen-Tag – der US-amerikanische National Kitten Day"],
  "07-11": ["Tag des Swimmingpools in den USA – National Swimming Pool Day","World Horse Day – der internationale UN-Welttag der Pferde","Día del Bandoneón – der argentinische Tag des Bandoneons","Tag der Haustierfotos in den USA – All American Pet Photo Day","Mojito-Tag – der US-amerikanische National Mojito Day","Weltbevölkerungstag am 11. Juli – der UNO World Population Day"],
  "07-12": ["Tag der Papiertüte am 12. Juli – National Paper Bag Day in den Vereinigten Staaten","Tag der Einfachheit am 12. Juli – National Simplicity Day in den Vereinigten Staaten"],
  "07-14": ["Tag des Grand Marnier am 14. Juli – National Grand Marnier Day in den USA","Tag der Haie am 14. Juli – National Shark Awareness Day in den Vereinigten Staaten","Ehrentag der Kuh in den USA – Cow Appreciation Day"],
  "07-15": ["Tag des Hot Dogs in den Vereinigten Staaten – National Hot Dog Day 15. Juli","Tag der Gummiwürmer am 15. Juli – National Gummi Worm Day in den USA"],
  "07-16": ["Der bundesweite Tag des guten Fleisches in Deutschland","Welttag der Schlange – der internationale World Snake Day"],
  "07-17": ["Tattoo-Tag – World Tattoo Day am 21. März und National Tattoo Day","Welt-Emoji-Tag am 17. Juli – der internationale World Emoji Day"],
  "07-18": ["Tag des Kaviars in den Vereinigten Staaten – National Caviar Day","Welt-Zuhör-Tag am 18. Juli – der internationale World Listening Day"],
  "07-19": ["Der bundesweite Tag der Zugverspätung in Deutschland","Simson-Tag – bundesweiter Aktionstag in Deutschland","Strecke-die-Zunge-raus-Tag am 19. Juli – Stick Out Your Tongue Day in den USA","Eiscreme-Tag in den USA – National Ice Cream Day","Tag des Daiquiri am 19. Juli – National Daiquiri Day in den Vereinigten Staaten"],
  "07-20": ["Internationaler Tag des Kuchens – der International Cake Day","World Jump Day – ein kollektiver Sprung der Menschheit","Lollipop-Tag am 20. Juli – National Lollipop Day in den Vereinigten Staaten","Internationaler Schach-Tag – International Chess Day – Happy Birthday, FIDE","Internationaler Tag des Ambigramms – International Ambigram Day"],
  "07-21": ["National Be Someone Day in den Vereinigten Staaten"],
  "07-22": ["Tag der Mango in den USA – National Mango Day"],
  "07-23": ["Tag der Schorle in Deutschland","International Yada, Yada, Yada Day – Yada-Yada-Yada-Tag","Tag der Erfrischungen in den USA – National Refreshment Day","Vanilleeis-Tag – der US-amerikanische National Vanilla Ice Cream Day"],
  "07-24": ["Tag des Drive-in – der US-amerikanische National Drive-Thru Day","Tag des Tequila – der US-amerikanische National Tequila Day","Internationaler Tag der Freude – International Day of Joy"],
  "07-25": ["Jakobstag oder Jakobitag – Lostag zu Ehren des Apostels Jakobus","Tag des Cowboy in den USA – National Day of the Cowboy"],
  "07-26": ["Welttag des Tofu – der internationale World Tofu Day","Der bundesweite Tag der Seenotretter in Deutschland","Tag des Bagelfests – der US-amerikanische National Bagelfest Day"],
  "07-27": ["Tag des Scotchs – der US-amerikanische National Scotch Day","Tag des Stelzenlaufens – der US-amerikanische Walk On Stilts Day"],
  "07-28": ["Tag des Kaffeesatzes in Deutschland","Welttag des Naturschutzes am 28. Juli – World Nature Conservation Day"],
  "07-29": ["Tag der Lasagne am 29. Juli – National Lasagna Day in den Vereinigten Staaten"],
  "07-30": ["Der internationale Weltpostkartentag","Der bundesweite Zuspätkommtag in Deutschland","Tag des Käsekuchens in den USA – National Cheesecake Day"],
  "07-31": ["Black Tot Day in Großbritannien – Gedenktag der letzten offiziellen Rumration","Tag der Avocado am 31. Juli – National Avocado Day in den USA","Harry Potters Geburtstag","Tag des Mischlingshundes am 31. Juli und 2. Dezember – National Mutt Day in den USA","Tag der Zuckerwatte am 31. Juli und 7. Dezember – National Cotton Candy Day in den USA"],
  "08-01": ["Tag der Sandburg in den USA – (National) Sandcastle Day","Der nationale Tag der Alpakas in Peru – Dia Nacional del Alpaca","Internationaler Tag des Blues – International Blues Music Day","Spider-Man-Tag am 1. August – National Spider-Man Day in den USA","Tag des Senfs in den USA – National Mustard Day","Freundinnen-Tag am 1. August – National Girlfriends Day in den USA"],
  "08-02": ["Tag der Dinosaurier am 2. August – National Dinosaurs Day in den USA","Tag der Puppen in den USA – National Doll Day","Tag der Schwestern in den USA – National Sisters Day","Sandwich-Eis-Tag am 2. August – National Ice Cream Sandwich Day in den USA"],
  "08-03": ["Tag der Wassermelone am 3. August – National Watermelon Day in den USA"],
  "08-05": ["Tag der grünen Paprika am 5. August – National Green Peppers Day in den USA","Tag der Auster – der US-amerikanische National Oyster Day"],
  "08-07": ["Tag der Drehtür – Theophilus Van Kannel erhält am 7. August 1888 das US-Patent für die Drehtür","Internationaler Tag des Bieres – International Beer Day","Tag des Leuchtturms in den USA – National Lighthouse Day"],
  "08-08": ["Memento Tag in Deutschland","Tag des Dollars am 8. August – National Dollar Day in den Vereinigten Staaten"],
  "08-09": ["Tag der Melone in Turkmenistan","Ehrentag der Kunst am 9. August – International Art Appreciation Day"],
  "08-10": ["S‘Mores-Tag am 10. August – der National S’Mores Day in den Vereinigten Staaten","Faulpelz-Tag in den Vereinigten Staaten – National Lazy Day","Welt-Löwen-Tag am 10. August – der internationale World Lion Day"],
  "08-11": ["Tag des Weizens in Deutschland","Yama no hi – 山の日 – der nationale Tag des Berges in Japan","Spiel-im-Sand-Tag am 11. August – National Play in the Sand Day in den USA"],
  "08-12": ["Tag der Mittelkinder am 12. August – National Middle Child‘s Day in den USA","Welttag des Elefanten – World Elephant Day"],
  "08-13": ["Prosecco-Tag – der US-amerikanische National Prosecco Day","Internationaler Linkshändertag – International Lefthanders Day"],
  "08-14": ["Welttag der Eidechsen – World Lizard Day"],
  "08-15": ["Tag der Fehler am 15. August – National Failures Day in den Vereinigten Staaten","Beste-Freunde-Tag am 8. Juni und 15. August – National Best Friends Day in den USA","Tag der Honigbiene in den USA – National Honey Bee Day"],
  "08-16": ["Welttag des Helikopters – der World Helicopter Day","Tag des Rums – der US-amerikanische National Rum Day","Tag der Achterbahn am 16. August – National Roller Coaster Day in den USA"],
  "08-17": ["Tag des HB-Bleistifts – der US-amerikanische National #2 Pencil Day"],
  "08-18": ["Tag der Papierformate – Publikation der Norm DIN 476","Tag der Eiscreme-Torte am 18. August – National Ice Cream Pie Day in den USA","Tag der Entdeckung des Elements Helium durch Jules Janssen","Tag der schlechten Poesie am 18. August – Bad Poetry Day in den USA","Tag des hochgekrempelten Hosenbeins in Deutschland"],
  "08-19": ["Softeis-Tag in den Vereinigten Staaten – National Soft Ice Cream Day","Sprich-wie-Jar-Jar-Binks-Tag – International Talk Like Jar Jar Binks Day","Das chinesische Fest Qixi – Elsterfest oder die Nacht der Siebenen","Internationaler Tag der Haarschleife – International Bow Day","Internationaler Tag des Orang-Utans – International Orangutan Day","Welt-Foto-Tag – World Photo Day oder World Photography Day"],
  "08-20": ["Endlich-kaputt-Tag in Deutschland","Tag der Limonade am 20. August – National Lemonade Day in den USA"],
  "08-21": ["Spumoni-Tag am 21. August – National Spumoni Day in den USA","Tag der Dichter am 21. August – der US-amerikanische National Poets Day","Tag der Männerpflege in den USA – Men’s Grooming Day"],
  "08-22": ["Weltpflanzenmilchtag – der internationale World Plant Milk Day","Tag der Fische in Deutschland"],
  "08-23": ["World Daffodil Day – Welttag der Narzisse"],
  "08-24": ["La Noche de la Nostalgia – die Nacht der Nostalgie in Uruguay","Tag des Messers am 24. August – National Knife Day in den Vereinigten Staaten"],
  "08-25": ["The Great Moon Hoax oder der Tag des großen Mondschwindels","Tag der Konservendose: Peter Durand erhält das Patent für die Konserve"],
  "08-26": ["Tag des Hundes in den Vereinigten Staaten – National Dog Day"],
  "08-27": ["Welttag der Seen – der United Nations World Lake Day","Tag des Tauziehens – der US-amerikanische Tug-of-War Day","Tag des Burgers in Großbritannien – National Burger Day","Einfach-so-Tag – der US-amerikanische Just because Day"],
  "08-28": ["Tag des Querbinders in den USA – National Bow Tie Day","Tag des Rotweins – der US-amerikanische National Red Wine Day"],
  "08-29": ["Tag der Individualrechte am 29. August – Individual Rights Day in den USA","Tag des Chop Suey am 29. August – National Chop Suey Day in den USA"],
  "08-30": ["Strand-Tag – der US-amerikanische National Beach Day","Tag des Slinky am 30. August – (National) Slinky Day in den USA"],
  "08-31": ["Iss-draußen-Tag am 31. August – der US-amerikanische Eat Outside Day"],
  "09-01": ["Welttag der Kuh – World Cow Day – internationaler Aktionstag","Internationaler Tag der Primaten am 1. September – International Primate Day","Der bundesweite Tag des Zebrastreifens in Deutschland","Welttag des Briefschreibens – World Letter Writing Day","Tag des Hühnerjungen am 1. September – National Chicken Boy Day in den USA"],
  "09-02": ["Bison-ten Yell Day in den Vereinigten Staaten","Internationaler Tag der Kokosnuss am 2. September – World Coconut Day"],
  "09-03": ["Tag des Feuersalamanders in Deutschland","Tag der Erbsensuppe in Deutschland"],
  "09-04": ["Iss-mehr-als-ein-Dessert-Tag am 4. September – Eat an Extra Dessert Day in den USA","Tag der Wildtiere am 22. Februar und 4. September – National Wildlife Day in den USA","Der bundesweite Tag der Currywurst in Deutschland","Tag des Zeitungsausträgers am 4. September – Newspaper Carrier Day in den USA"],
  "09-05": ["World Beard Day – Welttag des Bartes","Tag der Käsepizza am 5. September – National Cheese Pizza Day in den USA"],
  "09-06": ["Tag des Eierwerfens – der US-amerikanische Great Egg Toss Day","Pet-Rock-Tag in den Vereinigten Staaten – Pet Rock Day"],
  "09-07": ["Kauf-ein-Buch-Tag – der US-amerikanische National Buy a Book Day","(National) Salami Day – der US-amerikanische Tag der Salami"],
  "09-08": ["Star Trek Day – die TV-Premiere von Star Trek","Tag des Et-Zeichens am 8. September – National Ampersand Day in den USA","Der US-amerikanische National Ants On A Log Day","Internationaler Tag der Vergebung – der International Pardon Day"],
  "09-09": ["Internationaler Sudoku-Tag – International Sudoku Day","Internationaler Tag des typografisch richtigen Apostrophs","Das japanische Chrysanthemenfest Kiku no Sekku oder: Choyo no Sekku","Teddybär-Tag am 9. September – National Teddy Bear Day in den USA"],
  "09-10": ["Warntag in Deutschland – Probealarm","R U OK? Day in Australien – Aktionstag zur Suizidprävention"],
  "09-11": ["Die Earth Night in Deutschland und Österreich"],
  "09-12": ["Welttag der Ersten Hilfe – World First Aid Day","Tag der Delfine – National Dolphin Day am 14. April und World Dolphin Day"],
  "09-13": ["Der bundesweite Mach-was-du-willst-Tag in Deutschland","Internationaler Tag der Höhlen und der unterirdischen Welten am 6. Juni und 13. September","Glückskeks-Tag – der US-amerikanische National Fortune Cookie Day an 13. September","Internationaler Tag der Schokolade – der International Chocolate Day"],
  "09-14": ["Nutting Day am 14. September – Tag des Nüssesammelns in Großbritannien","Tag der Ruhe am 14. September – der britische National Quiet Day"],
  "09-15": ["Tag der IT-Profis in den USA – National IT Professionals Day","Internationaler Tag des Punktes – International Dot Day","Tag des Filzhuts am 15. September – National Felt Hat Day in den Vereinigten Staaten"],
  "09-17": ["Welttag der Mantarochen – World Manta Day"],
  "09-18": ["Welttag des Bambus – World Bamboo Day","Weltknotentag – World Knot Tying Day","Internationaler Parking Day – internationaler Aktionstag","Tag des Respekts am 18. September – der National Respect Day in den USA"],
  "09-19": ["Miaue-wie-ein-Pirat-Tag am 19. September – Meow Like a Pirate Day in den USA","Tag der Astronomie in den USA – National Astronomy Day am 25. April und 19. September"],
  "09-20": ["Tag der Schiene in Deutschland – 18. bis 20. September","Tag des Friedhofs in Deutschland – 19. und 20. September","Weltaufräumtag – World Cleanup Day"],
  "09-21": ["Achtung-vor-dem-Alter-Tag in Japan – Keirō no Hi"],
  "09-22": ["Autofreier Tag – World Car Free Day","Welt-Nashorn-Tag – World Rhino Day"],
  "09-23": ["Tag der Kastanie in Deutschland","Tag der Bisexualität – Celebrate Bisexuality Day"],
  "09-24": ["Weltschifffahrtstag – der World Maritime Day"],
  "09-25": ["Save the Koala Day in Australien – Rettet-die-Koalas-Tag","Tag der Comics am 25. September – National Comic Book Day in den USA"],
  "09-26": ["Tag der Geisterjagd in den USA – National Ghost Hunting Day","Tag der Pfannkuchen am 26. September – National Pancake Day in den USA","Europäischer Pilztag – der European Mushroom Day","Tag des Holzfällers am 26. September – der US-amerikanische Lumberjack Day"],
  "09-27": ["Tag des Schals am 27. September – National Scarf Day in den Vereinigten Staaten","Welttourismustag am 27. September – der internationale World Tourism Day","Internationaler Tag der Flüsse – World Rivers Day","Zerdrücke-eine-Dose-Tag am 27. September – National Crush a Can Day in den USA"],
  "09-28": ["Aquarium-Revue-Nacht am 28. September – Fish Tank Floorshow Night in den USA"],
  "09-29": ["Weltherztag 2026 – der internationale World Heart Day"],
  "09-30": ["Internationaler Podcast-Tag – International Podcast Day","Hieronymustag oder der Internationale Übersetzertag"],
  "10-01": ["Tag des CD-Players am 1. Oktober – National CD Player Day in den USA","Weltmusiktag oder Internationaler Tag der Musik – International Music Day"],
  "10-02": ["Der bundesweite Tag des Obstbrandes in Deutschland","Karo-Tag in den Vereinigten Staaten – National Plaid Day"],
  "10-03": ["Der weltweite Smoothie-Tag – Global Smoothie Day"],
  "10-04": ["Tag der Zimtschnecke – der schwedische Kanelbullens dag","Glühbirnen-Austausch-Tag in den USA – Change A Light Day","Welttierschutztag – der internationale World Animal Day"],
  "10-05": ["Internationaler Tag der Architektur – World Day of Architecture","Welt-Seifenblasen-Tag – der internationale World Bubble Day","Weltlehrertag – der internationale UNESCO World Teacher’s Day"],
  "10-06": ["Europäischer Tag der pflegenden Angehörigen – European Carers Day","Nudel-Tag – International Noodle Day for Raymond Federmann"],
  "10-07": ["Tag des Mineralwassers in Deutschland","Tag des Grünkohls in den USA – National Kale Day","Tag der Kürbiskerne in den USA – National Pumpkin Seed Day","Der bundesweite Tag des Morgenmuffels in Deutschland"],
  "10-08": ["Welttag der Kraken – World Octopus Day","Welttag des Sehens – der internationale World Sight Day","Tag der Piroggen am 8. Oktober – National Pierogi Day in den USA","Welttag der Buchhandlungen am 8. Oktober – World Bookshop Day","Tag des Fangspiels am 8. Oktober – American Touch Tag Day in den USA"],
  "10-09": ["Weltposttag oder Tag des Weltpostvereins – World Post Day","Hangeul-Tag in Südkorea – der Tag des koreanischen Alphabets an 9. Oktober","Welt-Ei-Tag – World Egg Day"],
  "10-10": ["Welttag des Porridge am 10. Oktober – World Porridge Day","Tag der Tic Tacs am 10. Oktober – National Tic Tac Day in den Vereinigten Staaten","Umarme-einen-Schlagzeuger-Tag am 10. Oktober – Hug a Drummer Day","Universaler Tag der Musik – Universal Music Day","Welthundetag oder Welttag des Hundes am 10. Oktober – World Dog Day"],
  "10-11": ["Der bundesweite Tag des Schauspiels in Deutschland","Meine-Party-Tag – der US-amerikanische It’s My Party Day"],
  "10-12": ["Freidenker-Tag – der US-amerikanische Freethought Day","Kolumbus-Tag in den USA – Columbus Day"],
  "10-13": ["M&#038;M-Tag – der US-amerikanische National M&#038;M Day","International Suit Up Day – zu Ehren von Barney Stinson"],
  "10-14": ["Weltnormentag – World Standards Day","Glücklich-trotz-Glatze-Tag am 14. Oktober – Be Bald &#038; be Free Day in den USA","Tag des Desserts am 14. Oktober – National Dessert Day in den Vereinigten Staaten"],
  "10-15": ["Tag des Schornsteinfegers in Deutschland"],
  "10-16": ["Ex-Tag – der US-amerikanische National Ex Day"],
  "10-17": ["Internationaler Tag der Reparatur – International Repair Day","Nationaler Pasta-Tag – der US-amerikanische National Pasta Day","Der Süßeste Tag in den Vereinigten Staaten – Sweetest Day"],
  "10-18": ["Tag der Krawatte in Kroatien – der kroatische Dan Kravate","Ohne-Bart-Tag – der US-amerikanische National No Beard Day"],
  "10-20": ["Tag der Allee in Deutschland – bundesweiter Aktionstag","Internationaler Tag der Köche am 20. Oktober – der International Chefs Day","Weltosteoporosetag am 20. Oktober – der World Osteoporosis Day"],
  "10-21": ["Tag des Apfels in Großbritannien – der nationale Apple Day UK","Tag der Kinderseiten in Deutschland"],
  "10-22": ["Tag des Wombats – der australische World Wombat Day","Tag der Farbe in den Vereinigten Staaten – National Color Day","Tag der Nuss in Großbritannien – der britische National Nut Day"],
  "10-24": ["Welttag der Gewürze – der internationale World Spice Day","Tag der Ernährung am 24. Oktober – der US-amerikanische National Food Day","Tag der Bibliotheken in Deutschland"],
  "10-25": ["Tag der Oper – National Opera Day am 8. Februar und World Opera Day","Der bundesweite Tag des Einbruchschutzes in Deutschland","Schwiegermutter-Tag in den USA – National Mother-in-Law Day","Welttag der Pizzabäcker 2026 – World Pizza Makers Day","Internationaler Tag der Künstler – International Artist Day","Tag des fettigen Essens am 25. Oktober – National Greasy Foods Day in den USA","Weltpastatag oder Weltnudeltag am 25. Oktober – der internationale World Pasta Day","Sourest Day – oder: Happy Birthday, Mr. Sauer -der Sauerste Tag des Jahres"],
  "10-27": ["Der bundesweite Mit-Absicht-Geld-verlieren-Tag in Deutschland"],
  "10-28": ["Ochi-Tag oder der Jahrestag des Nein in Griechenland"],
  "10-29": ["Tag der Katze in den Vereinigten Staaten – National Cat Day"],
  "10-30": ["Welttag des Hörspiels – World Audio Drama Day","Tag des Kinnkraulens am 30. Oktober in Deutschland","Bandana-Tag in Australien am 30. Oktober – National Bandana Day"],
  "10-31": ["Welttag der Städte – World Cities Day","Weltspartag – World Savings Day","Umarme-ein-Schaf-Tag in den USA – National Hug a Sheep Day"],
  "11-03": ["Welttag der Quallen – World Jellyfish Day"],
  "11-04": ["Tutanchamun-Tag – der internationale King Tut Day","Tag der Süßigkeiten am 4. November – National Candy Day in den USA"],
  "11-06": ["Tag des Füllfederhalters – der internationale Fountain Pen Day","Tag des Saxophons – der internationale Saxophone Day"],
  "11-07": ["Tag des Kladdkaka in Schweden – der Kladdkakans dag"],
  "11-08": ["Welttag der Stadtplanung – World Town Planinng Day","Internationaler Tag der Putzfrau – Weltputzfrauentag"],
  "11-09": ["Tag der Neon-Schilder am 9. November – National Neon Sign Day in den USA","Dia de los ñatitas am 9. November – der Tag der Totenschädel in Bolivien","Tag der Erfinder in Deutschland am 9. November – Happy Birthday Hedy Lamarr"],
  "11-10": ["Internationaler Tag der Buchhaltung – International Accounting Day","Tag der Tagespflegen – bundesweiter Aktionstag in Deutschland","Der bundesweite Sir-ja-Sir-Tag in Deutschland"],
  "11-11": ["Tag des Eisbechers am 11. November – National Sundae Day in den USA","Tag des Heavy Metal am 11. November – National Metal Day in den USA","Nigel Tufnel Day am 11. November – internatinaler Ehrentag der Maximum Eleveness","Tag des Weckmanns oder Tag des Stutenkerls in Deutschland – 11. November und 6. Dezember"],
  "11-12": ["Tag der schlechten Wortspiele in Deutschland"],
  "11-13": ["Sadie Hawkins Day in den USA","Welt-Nettigkeitstag – World Kindness Day"],
  "11-14": ["Tag der Gewürzgurke am 14. November – National Pickle Day in den USA"],
  "11-16": ["Tag des Knopfes am 16. November – National Button Day in den Vereinigten Staaten"],
  "11-17": ["Tag der Computermaus – US-Patetent an Douglas Engelbarter","Tag der Butter – der US-amerikanische National Butter Day","Baklava-Tag – der US-amerikanische National Baklava Day","Geh-wandern-Tag am 17. November – Take a Hike Day in den USA","Internationaler Wookiee Life Day auf Kashyyk"],
  "11-18": ["Mickey Mouse Day – der Geburtstag von Micky Maus","Tag des Okkultismus – der US-amerikanische National Occult Day"],
  "11-19": ["Internationaler Männertag – International Men’s Day","Welttag der Philosophie – UNESCO World Philosophy Day","Tag der Suppe in Deutschland – historischer Aktionstag","Welttoilettentag am 19. November – World Toilet Day"],
  "11-20": ["Vorlesetag – Deutschlands bundesweit größtes Vorlesefest","Der schöne Tag  – der US-amerikanische Beautiful Day"],
  "11-21": ["Tag ohne Musik – der internationale No Music Day","Welt-Hallo-Tag – World Hello Day – internationaler Aktionstag"],
  "11-22": ["Das Mariachi-Fest der heiligen Cäcilia in Mexiko","Mach-eine-Spritztour-Tag – der US-amerikanische Go For A Ride Day","Der bundesweite Tag der Hausmusik in Deutschland"],
  "11-23": ["Fibonacci-Tag – der US-amerikanische Fibonacci Day","Iss-eine-Cranberry-Tag am 23. November – National Eat a Cranberry Day in den USA","Tag des Dankes für die Arbeit in Japan – Kinrô kansha no hi"],
  "11-24": ["Internationaler Tag des Lettering","Tag der Heimlichkeiten in Deutschland","Tag der Gummistiefel in Deutschland","Walross-Tag in Russland"],
  "11-25": ["Tag des Parfait – der US-amerikanische National Parfait Day"],
  "11-26": ["Welttag des Olivenbaums – World Olive Tree Day","Tag des Kuchens – der US-amerikanische National Cake Day","Welttag der Zeitschriften – internationale Aktionstag"],
  "11-27": ["Über-der-Spüle-Essen-Tag in den USA – Sinkie Day","Tag des Streichholzes zu Ehren von John Walker","Kauf-nix-Tag in den USA – National Buy Nothing Day"],
  "11-28": ["Welttag der Barmherzigkeit – World Compassion Day"],
  "11-29": ["Tag des Adventskranzes zum ersten Adventssonntag"],
  "11-30": ["Tag der Mousse – der US-amerikanische National Mousse Day","Tag der blauen Mütze – der internationale Blue Beanie Day"],
  "12-01": ["Der bundesweite Tag der Trinkwasserhygiene in Deutschland","Mistelzweig-Tag – National Mistletoe Day in Großbritannien","Der bundesweite Tag des Adventskalenders in Deutschland","Welt-AIDS-Tag 2026 – der internationale World AIDS Day"],
  "12-02": ["Tag der Spekulatius in Deutschland","Der internationale Tag der Modelleisenbahn","Tag des Mischlingshundes am 31. Juli und 2. Dezember – National Mutt Day in den USA","Tag der Krapfen – der US-amerikanische National Fritters Day","Tag des Sicherheitsrasierers am 2. Dezember – Safety Razor Day in den USA"],
  "12-03": ["Tag der Dominosteine in Deutschland"],
  "12-04": ["Welttag der Tunnel – World Tunnel Day – internationaler Aktionstag","Internationaler Tag des Geparden – der International Cheetah Day","Tag der Socke am 4. Dezember – National Sock Day in den Vereinigten Staaten"],
  "12-05": ["Candle Day in den Vereinigten Staaten – Tag der Kerzen","Internationaler Tag des Ninja – der International Day of the Ninja","Badewannen-Party-Tag – der US-amerikanische Bathtub Party Day"],
  "12-06": ["Tag des Weckmanns oder Tag des Stutenkerls in Deutschland – 11. November und 6. Dezember","Der bundesweite Tag des Schokoladennikolaus in Deutschland"],
  "12-07": ["Internationaler Tag des Honigs","Tag der Weihnachtskrippe in Deutschland","Tag der Zuckerwatte am 31. Juli und 7. Dezember – National Cotton Candy Day in den USA"],
  "12-08": ["Der bundesweite Krimitag","Welttag der Erstimpfung","Tag des Brownies am 8. Dezember – National Brownie Day in den Vereinigten Staaten"],
  "12-09": ["Tag des Lamas – National Llama Day in Kanada und den USA","Tag des Feingebäcks am 9. Dezember – National Pastry Day in den USA","Tag der Weihnachtskarte am 9. Dezember – Christmas Card Day in den USA"],
  "12-10": ["Tag des Christstollens in Deutschland"],
  "12-11": ["Tag der Zimtsterne in Deutschland"],
  "12-12": ["Tag des Baumkuchens in Deutschland"],
  "12-13": ["Welttag der Chöre – der internationale World Choral Day","Tag der Seeleute in Brasilien – Dia do Marinheiro für Joaquim Marques Lisboa","Tag der Geige – der US-amerikanische National Violin Day"],
  "12-14": ["Welttag des Eislaufens – der World Ice Skating Day","Tag der Schneekugel in Deutschland","Affentag oder Tag der Affen – Monkey Day"],
  "12-15": ["Tag des Weihnachtsbaums aus Büchern in Deutschland","Internationaler Tee-Tag – der International Tea Day am 21. Mai und","Cupcake-Tag – der US-amerikanische National Cupcake Day"],
  "12-16": ["Bundesweiter Tag des Tannenzapfens in Deutschland","Tag der Versöhnung in Südafrika – Day of Reconciliation"],
  "12-19": ["Tag der Bonbons – der US-amerikanische National Hard Candy Day","Tag der Stechpalme – der US-amerikanische Holly Day","Tag der Weihnachtskugeln – ein Feiertag für die Christbaumkugel"],
  "12-20": ["Games Day in Großbritannien – der englische Tag der Spiele","Tag des Sternsingens – der US-amerikanische Go Caroling Day","Sangria-Tag in den Vereinigten Staaten – National Sangria Day"],
  "12-21": ["Beginn der Rauhnächte am 21. Dezember oder 24. Dezember","Hiwatari Matsuri – das japanische Feuerlauf-Fest"],
  "12-22": ["Tag des Weihnachtsgebäcks in Deutschland","Tag der Vorväter – der US-amerikanische Forefather’s Day"],
  "12-23": ["Festivus in den USA – A Festivus for the rest of us"],
  "12-24": ["Jólabókaflóð – die Weihnachtsbücherflut in Island","Tag des Kartoffelsalats mit Würstchen in Deutschland","Tag des Eierflips am 24. Dezember – National Eggnog Day in den Vereinigten Staaten"],
  "12-27": ["Eröffnungstag der Radio City Music Hall in New York"],
  "12-28": ["Tag des Rühreis in Deutschland"],
  "12-29": ["Tag des Spiegeleis in Deutschland"],
  "12-31": ["Silvester – 31. Dezember – der letzte Tag des Jahres"],
};
