/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HotlineRouteImport } from './routes/hotline'
import { Route as LiveStreamRouteImport } from './routes/live-stream'
import { Route as PlayerRouteImport } from './routes/player'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as WerbungRouteImport } from './routes/werbung'
import { Route as ApiAudioRouteImport } from './routes/api/audio'
import { Route as ApiEngineSkipRouteImport } from './routes/api/engine-skip'
import { Route as ApiFreemusicRouteImport } from './routes/api/freemusic'
import { Route as ApiIcecastMetadataRouteImport } from './routes/api/icecast-metadata'
import { Route as ApiMediaRouteImport } from './routes/api/media'
import { Route as ApiNewsRouteImport } from './routes/api/news'
import { Route as ApiNewsroomRouteImport } from './routes/api/newsroom'
import { Route as ApiScriptRouteImport } from './routes/api/script'
import { Route as ApiStreamhealthRouteImport } from './routes/api/streamhealth'
import { Route as ApiTrafficRouteImport } from './routes/api/traffic'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiPublicAdRequestsRouteImport } from './routes/api/public/ad-requests'
import { Route as ApiPublicHotlineRouteImport } from './routes/api/public/hotline'
import { Route as ApiPublicNowplayingRouteImport } from './routes/api/public/nowplaying'
import { Route as ApiPublicOnairAudioRouteImport } from './routes/api/public/onair-audio'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotlineRoute = HotlineRouteImport.update({
  id: '/hotline',
  path: '/hotline',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveStreamRoute = LiveStreamRouteImport.update({
  id: '/live-stream',
  path: '/live-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerRoute = PlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const WerbungRoute = WerbungRouteImport.update({
  id: '/werbung',
  path: '/werbung',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAudioRoute = ApiAudioRouteImport.update({
  id: '/api/audio',
  path: '/api/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEngineSkipRoute = ApiEngineSkipRouteImport.update({
  id: '/api/engine-skip',
  path: '/api/engine-skip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFreemusicRoute = ApiFreemusicRouteImport.update({
  id: '/api/freemusic',
  path: '/api/freemusic',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIcecastMetadataRoute = ApiIcecastMetadataRouteImport.update({
  id: '/api/icecast-metadata',
  path: '/api/icecast-metadata',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaRoute = ApiMediaRouteImport.update({
  id: '/api/media',
  path: '/api/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsRoute = ApiNewsRouteImport.update({
  id: '/api/news',
  path: '/api/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsroomRoute = ApiNewsroomRouteImport.update({
  id: '/api/newsroom',
  path: '/api/newsroom',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScriptRoute = ApiScriptRouteImport.update({
  id: '/api/script',
  path: '/api/script',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamhealthRoute = ApiStreamhealthRouteImport.update({
  id: '/api/streamhealth',
  path: '/api/streamhealth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrafficRoute = ApiTrafficRouteImport.update({
  id: '/api/traffic',
  path: '/api/traffic',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdRequestsRoute = ApiPublicAdRequestsRouteImport.update({
  id: '/api/public/ad-requests',
  path: '/api/public/ad-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHotlineRoute = ApiPublicHotlineRouteImport.update({
  id: '/api/public/hotline',
  path: '/api/public/hotline',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNowplayingRoute = ApiPublicNowplayingRouteImport.update({
  id: '/api/public/nowplaying',
  path: '/api/public/nowplaying',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOnairAudioRoute = ApiPublicOnairAudioRouteImport.update({
  id: '/api/public/onair-audio',
  path: '/api/public/onair-audio',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hotline': typeof HotlineRoute
  '/live-stream': typeof LiveStreamRoute
  '/player': typeof PlayerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/werbung': typeof WerbungRoute
  '/api/audio': typeof ApiAudioRoute
  '/api/engine-skip': typeof ApiEngineSkipRoute
  '/api/freemusic': typeof ApiFreemusicRoute
  '/api/icecast-metadata': typeof ApiIcecastMetadataRoute
  '/api/media': typeof ApiMediaRoute
  '/api/news': typeof ApiNewsRoute
  '/api/newsroom': typeof ApiNewsroomRoute
  '/api/script': typeof ApiScriptRoute
  '/api/streamhealth': typeof ApiStreamhealthRoute
  '/api/traffic': typeof ApiTrafficRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/public/ad-requests': typeof ApiPublicAdRequestsRoute
  '/api/public/hotline': typeof ApiPublicHotlineRoute
  '/api/public/nowplaying': typeof ApiPublicNowplayingRoute
  '/api/public/onair-audio': typeof ApiPublicOnairAudioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hotline': typeof HotlineRoute
  '/live-stream': typeof LiveStreamRoute
  '/player': typeof PlayerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/werbung': typeof WerbungRoute
  '/api/audio': typeof ApiAudioRoute
  '/api/engine-skip': typeof ApiEngineSkipRoute
  '/api/freemusic': typeof ApiFreemusicRoute
  '/api/icecast-metadata': typeof ApiIcecastMetadataRoute
  '/api/media': typeof ApiMediaRoute
  '/api/news': typeof ApiNewsRoute
  '/api/newsroom': typeof ApiNewsroomRoute
  '/api/script': typeof ApiScriptRoute
  '/api/streamhealth': typeof ApiStreamhealthRoute
  '/api/traffic': typeof ApiTrafficRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/public/ad-requests': typeof ApiPublicAdRequestsRoute
  '/api/public/hotline': typeof ApiPublicHotlineRoute
  '/api/public/nowplaying': typeof ApiPublicNowplayingRoute
  '/api/public/onair-audio': typeof ApiPublicOnairAudioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hotline': typeof HotlineRoute
  '/live-stream': typeof LiveStreamRoute
  '/player': typeof PlayerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/werbung': typeof WerbungRoute
  '/api/audio': typeof ApiAudioRoute
  '/api/engine-skip': typeof ApiEngineSkipRoute
  '/api/freemusic': typeof ApiFreemusicRoute
  '/api/icecast-metadata': typeof ApiIcecastMetadataRoute
  '/api/media': typeof ApiMediaRoute
  '/api/news': typeof ApiNewsRoute
  '/api/newsroom': typeof ApiNewsroomRoute
  '/api/script': typeof ApiScriptRoute
  '/api/streamhealth': typeof ApiStreamhealthRoute
  '/api/traffic': typeof ApiTrafficRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/public/ad-requests': typeof ApiPublicAdRequestsRoute
  '/api/public/hotline': typeof ApiPublicHotlineRoute
  '/api/public/nowplaying': typeof ApiPublicNowplayingRoute
  '/api/public/onair-audio': typeof ApiPublicOnairAudioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hotline'
    | '/live-stream'
    | '/player'
    | '/sitemap.xml'
    | '/werbung'
    | '/api/audio'
    | '/api/engine-skip'
    | '/api/freemusic'
    | '/api/icecast-metadata'
    | '/api/media'
    | '/api/news'
    | '/api/newsroom'
    | '/api/script'
    | '/api/streamhealth'
    | '/api/traffic'
    | '/api/tts'
    | '/api/public/ad-requests'
    | '/api/public/hotline'
    | '/api/public/nowplaying'
    | '/api/public/onair-audio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hotline'
    | '/live-stream'
    | '/player'
    | '/sitemap.xml'
    | '/werbung'
    | '/api/audio'
    | '/api/engine-skip'
    | '/api/freemusic'
    | '/api/icecast-metadata'
    | '/api/media'
    | '/api/news'
    | '/api/newsroom'
    | '/api/script'
    | '/api/streamhealth'
    | '/api/traffic'
    | '/api/tts'
    | '/api/public/ad-requests'
    | '/api/public/hotline'
    | '/api/public/nowplaying'
    | '/api/public/onair-audio'
  id:
    | '__root__'
    | '/'
    | '/hotline'
    | '/live-stream'
    | '/player'
    | '/sitemap.xml'
    | '/werbung'
    | '/api/audio'
    | '/api/engine-skip'
    | '/api/freemusic'
    | '/api/icecast-metadata'
    | '/api/media'
    | '/api/news'
    | '/api/newsroom'
    | '/api/script'
    | '/api/streamhealth'
    | '/api/traffic'
    | '/api/tts'
    | '/api/public/ad-requests'
    | '/api/public/hotline'
    | '/api/public/nowplaying'
    | '/api/public/onair-audio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HotlineRoute: typeof HotlineRoute
  LiveStreamRoute: typeof LiveStreamRoute
  PlayerRoute: typeof PlayerRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WerbungRoute: typeof WerbungRoute
  ApiAudioRoute: typeof ApiAudioRoute
  ApiEngineSkipRoute: typeof ApiEngineSkipRoute
  ApiFreemusicRoute: typeof ApiFreemusicRoute
  ApiIcecastMetadataRoute: typeof ApiIcecastMetadataRoute
  ApiMediaRoute: typeof ApiMediaRoute
  ApiNewsRoute: typeof ApiNewsRoute
  ApiNewsroomRoute: typeof ApiNewsroomRoute
  ApiScriptRoute: typeof ApiScriptRoute
  ApiStreamhealthRoute: typeof ApiStreamhealthRoute
  ApiTrafficRoute: typeof ApiTrafficRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ApiPublicAdRequestsRoute: typeof ApiPublicAdRequestsRoute
  ApiPublicHotlineRoute: typeof ApiPublicHotlineRoute
  ApiPublicNowplayingRoute: typeof ApiPublicNowplayingRoute
  ApiPublicOnairAudioRoute: typeof ApiPublicOnairAudioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotline': {
      id: '/hotline'
      path: '/hotline'
      fullPath: '/hotline'
      preLoaderRoute: typeof HotlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-stream': {
      id: '/live-stream'
      path: '/live-stream'
      fullPath: '/live-stream'
      preLoaderRoute: typeof LiveStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player': {
      id: '/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof PlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/werbung': {
      id: '/werbung'
      path: '/werbung'
      fullPath: '/werbung'
      preLoaderRoute: typeof WerbungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audio': {
      id: '/api/audio'
      path: '/api/audio'
      fullPath: '/api/audio'
      preLoaderRoute: typeof ApiAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/engine-skip': {
      id: '/api/engine-skip'
      path: '/api/engine-skip'
      fullPath: '/api/engine-skip'
      preLoaderRoute: typeof ApiEngineSkipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/freemusic': {
      id: '/api/freemusic'
      path: '/api/freemusic'
      fullPath: '/api/freemusic'
      preLoaderRoute: typeof ApiFreemusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/icecast-metadata': {
      id: '/api/icecast-metadata'
      path: '/api/icecast-metadata'
      fullPath: '/api/icecast-metadata'
      preLoaderRoute: typeof ApiIcecastMetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media': {
      id: '/api/media'
      path: '/api/media'
      fullPath: '/api/media'
      preLoaderRoute: typeof ApiMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news': {
      id: '/api/news'
      path: '/api/news'
      fullPath: '/api/news'
      preLoaderRoute: typeof ApiNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/newsroom': {
      id: '/api/newsroom'
      path: '/api/newsroom'
      fullPath: '/api/newsroom'
      preLoaderRoute: typeof ApiNewsroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/script': {
      id: '/api/script'
      path: '/api/script'
      fullPath: '/api/script'
      preLoaderRoute: typeof ApiScriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/streamhealth': {
      id: '/api/streamhealth'
      path: '/api/streamhealth'
      fullPath: '/api/streamhealth'
      preLoaderRoute: typeof ApiStreamhealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/traffic': {
      id: '/api/traffic'
      path: '/api/traffic'
      fullPath: '/api/traffic'
      preLoaderRoute: typeof ApiTrafficRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ad-requests': {
      id: '/api/public/ad-requests'
      path: '/api/public/ad-requests'
      fullPath: '/api/public/ad-requests'
      preLoaderRoute: typeof ApiPublicAdRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hotline': {
      id: '/api/public/hotline'
      path: '/api/public/hotline'
      fullPath: '/api/public/hotline'
      preLoaderRoute: typeof ApiPublicHotlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/nowplaying': {
      id: '/api/public/nowplaying'
      path: '/api/public/nowplaying'
      fullPath: '/api/public/nowplaying'
      preLoaderRoute: typeof ApiPublicNowplayingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/onair-audio': {
      id: '/api/public/onair-audio'
      path: '/api/public/onair-audio'
      fullPath: '/api/public/onair-audio'
      preLoaderRoute: typeof ApiPublicOnairAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HotlineRoute: HotlineRoute,
  LiveStreamRoute: LiveStreamRoute,
  PlayerRoute: PlayerRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WerbungRoute: WerbungRoute,
  ApiAudioRoute: ApiAudioRoute,
  ApiEngineSkipRoute: ApiEngineSkipRoute,
  ApiFreemusicRoute: ApiFreemusicRoute,
  ApiIcecastMetadataRoute: ApiIcecastMetadataRoute,
  ApiMediaRoute: ApiMediaRoute,
  ApiNewsRoute: ApiNewsRoute,
  ApiNewsroomRoute: ApiNewsroomRoute,
  ApiScriptRoute: ApiScriptRoute,
  ApiStreamhealthRoute: ApiStreamhealthRoute,
  ApiTrafficRoute: ApiTrafficRoute,
  ApiTtsRoute: ApiTtsRoute,
  ApiPublicAdRequestsRoute: ApiPublicAdRequestsRoute,
  ApiPublicHotlineRoute: ApiPublicHotlineRoute,
  ApiPublicNowplayingRoute: ApiPublicNowplayingRoute,
  ApiPublicOnairAudioRoute: ApiPublicOnairAudioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
